_target_: lfads_torch.models.base_model.LFADS

# --------- architecture --------- #
data_dim: 50
ext_input_dim: 0
seq_len: 100
ic_enc_seq_len: 0
ic_enc_dim: 128
ci_enc_dim: 128
ci_lag: 1
con_dim: 128
co_dim: 1
ic_dim: 64
gen_dim: 200
fac_dim: 50

# --------- dropout --------- #
dropout_rate: 0.05
cd_rate: 0.0
cd_pass_rate: 0.0
sv_rate: 0.0
sv_seed: 0

# --------- priors / posteriors --------- #
recon_type: Poisson
sample_posteriors: True
co_prior_var: 0.1
ic_prior_var: 0.1
ic_post_var_min: 1.0e-4

# --------- misc --------- #
cell_clip: 5.0
loss_scale: 10_000
recon_reduce_mean: True

# --------- learning rate --------- #
lr_init: 0.01
lr_stop: 1.0e-5
lr_decay: 0.95
lr_patience: 6
lr_adam_epsilon: 1.0e-7

# --------- regularization --------- #
l2_start_epoch: 0
l2_increase_epoch: 500
l2_ic_enc_scale: 0.0
l2_ci_enc_scale: 0.0
l2_gen_scale: 2.0e+4
l2_con_scale: 0.0
kl_start_epoch: 0
kl_increase_epoch: 500
kl_ic_scale: 1.0
kl_co_scale: 1.0
