_target_: lfads_torch.datamodules.nlb.LFADSNLBDataModule
dataset_name: mc_rtt
phase: val
bin_width: 5
batch_size: 256
# Name with `dm_` to avoid overlap w/ model HPS (per `pytorch_lightning==1.4.9`)
dm_ic_enc_seq_len: ${model.ic_enc_seq_len}
