_target_: lfads_torch.datamodules.BasicDataModule
data_paths:
  - ${relpath:datasets/mc_rtt-05ms-val.h5}
batch_keys:
  - behavior
attr_keys:
  - train_decode_mask
  - valid_decode_mask
batch_size: 256
